### ISSUE TITLE
Open a specific tab using a link

### ISSUE THREAD

**Issue by tobstop** [samsono/Easy-Responsive-Tabs-to-Accordion#1]
Hi,

great plugin!
Is it possible to open a specific tab using a link (on the same page)?

**Comment by samsono** [comment]
Hi,

Thanks for using this plugin, here is the simple solution.
1. Add an "Id" to tab li for eg &lt;li id="openTab"&gt;tab heading&lt;/li&gt;
2. Call the below function on "click".
   <pre><code>
   function(){
      $('#openTab').click();
   }
   </code></pre>

**Comment by ghost** [comment]
Awesome plugin, thanks. How about opening a specific tab from a link on a different page?

**Comment by ghost** [comment]
```
// if the URL contains a hashtag, trigger click on that tab.
if (window.location.hash !== '') {
    var thisUrlHash = window.location.hash;
    $('#DivTagName').find(thisUrlHash).click();
}
```

I called this in a separate js file.

**Comment by ginanjarputra** [comment]
can i see full code for opening a specific tab from different page?
