### ISSUE TITLE
Linking to tabs doesn't work when linking to a tab like an in-page anchor

### ISSUE THREAD

**Issue by izziebee** [samsono/Easy-Responsive-Tabs-to-Accordion#19]
Linking to tabs works great if the link is one on page (say test.shtml) and the tab is on another page (say index.shtml). 

If I am on index.shtml and I have text on tab 1 that links to tab 2 (also on the index page), how do I do that? 

Upon implementing the new instructions, the URL changes to the appropriate tab but the content on the page doesn't switch to the new tab.

Thanks!

**Comment by samsono** [comment]
Plugin is working fine with the another page link, please check your code once it should work. or share with us will look into the issue. Thanks

**Comment by jaygao79** [comment]
Any idea how to get it to work on the same page? For example, a link in the content of tab1 links to tab2, but when click on that link, the # is changed, but tab2 does not open.

Thanks,

**Comment by izziebee** [comment]
I am still unable to get links to work between tabs on the same page.

**Comment by jaygao79** [comment]
Please go to unclosed issues, the bottom of the name of tabs issue, see @suenotsuan's solution.
It works and I tested.

**Comment by izziebee** [comment]
@jaygao79 do you have an example URL where you have this working? I'd like to take a look at an example. Thanks!

**Comment by ghost** [comment]
Unfortunately my site redo is still on the Development server and can't be seen outside of my company.

**Comment by jaygao79** [comment]
@izziebee same here, my site is local on my machine. But I can confirm that by adding suenotosuan's code to the page, it works.
