### ISSUE TITLE
Nested tabs?

### ISSUE THREAD

**Issue by Fatbat** [samsono/Easy-Responsive-Tabs-to-Accordion#2]
Hello. I would very much like to nest the vertical tabs within the horizontal ones. For example, I'd like to have a row of 6 horizontal tabs, and inside each of those would like a column of 8 vertical tabs. Can you think of an easy way to do this? I've tried it myself but haven't had any luck.

Thanks.

**Comment by Reem-Alatrash** [comment]
I second that! nested tabs (vertical tabs within the horizontal ones) would be great! :)

**Comment by samsono** [comment]
I am working on it, will release as soon as possible..

**Comment by mikeslim7** [comment]
Hi Samson, 

I have added the nested tabs feature to your plugin. You can see it here: http://mikeslim7.github.io/Easy-Responsive-Tabs-to-Accordion/

Regards,
Mike.

**Comment by fourpixels** [comment]
As far as I can see - there's no update on this one, so at least merge with @mikeslim7 
He's solution is not perfect (adds some css things that messed up everything), but despite that - works like a charm :)

**Comment by mikeslim7** [comment]
Thanks @fourpixels! Yes I would not mind a cleaner solution for sure :-)

**Comment by nikki89** [comment]
i have used easy responsive tabs i want to use horizontal tabs within vertical tabs 
is there any solution ?
