### ISSUE TITLE
Linking to Tabs: Use Tab Name istead of Number

### ISSUE THREAD

**Issue by holzhannes** [samsono/Easy-Responsive-Tabs-to-Accordion#21]
Would it be possible to extend the plugin, so that it is possible to link directly to a content with using the title for the anchor link instead of the number?

Example
Three Tabs with the names: Cars, Bikes, Planes
If I Like to link to Bikes I would use http://yoursite.com/tabs.html#{TAB ID}2

I think the plugin would be more flexible and SEO friendly if it would be possilbe to link to http://yoursite.com/tabs.html#Bikes instead.

Do you think this is possible?

**Comment by samsono** [comment]
Thanks for your feedback will on this.
