### ISSUE TITLE
Linking to Tabs - I Can't make it work

### ISSUE THREAD

**Issue by diegocanal** [samsono/Easy-Responsive-Tabs-to-Accordion#23]
Hi @samsono,

First of all, thank you so much for such a great plugin.

I am following your instructions but I must be doing something wrong.

I was wondering if you could possibly include an a couple of links-to-tabs in the index.html so they can serve as examples.

Thanks.

Best Regards

**Comment by skald1** [comment]
Same problem here.

**Comment by peterlockhart** [comment]
It works fine for me if I'm linking to a tab from another page, but I have a button on the same page as the tabs that I would like to make a certain tab active, but it doesn't work.

**Comment by samsono** [comment]
It works fine.. plz cross check the code.
