### ISSUE TITLE
Does not work with latest jQuery

### ISSUE THREAD

**Issue by pantone204** [samsono/Easy-Responsive-Tabs-to-Accordion#25]
Bummer.

**Comment by nicolalongo** [comment]
I'm trying it with jquery 1.10 but it seems to doesn't work. 
Did you fix this issue in the Easy-Responsive-Tab-to-Accordion download version?

**Comment by samsono** [comment]
Friend its working fine with all latest jQuery file, please check your solution. Thanks for using.
http://code.jquery.com/jquery-2.0.2.min.js
http://code.jquery.com/jquery-1.10.1.min.js

**Comment by pantone204** [comment]
Not last time I checked. Found something else anyway.

**Comment by nicolalongo** [comment]
Sorry Samsono,

I check and fix the problem. They work well
