### ISSUE TITLE
Linking from another page, tab open

### ISSUE THREAD

**Issue by chipgrafx** [samsono/Easy-Responsive-Tabs-to-Accordion#5]
I think this is related to the "Open a specific tab using a link" issue that is already closed...

I have some navigation items on the homepage of a site. Each item (or Problem) links to a specific tab (or Solution) within a single Solutions page. Each tab is a solution to a different problem.

How can I do this so that when a Problem link is clicked the corresponding Solution tab is open when the page loads?

I am somewhat familiar with jQuery but I am by no means an expert. The answer to the previous issue similar to mine did not resolve my problem. Thanks for your help. These tabs are great!

**Comment by ghost** [comment]
Hi chipgrafx, did you manage to achieve this? I really need to do the same thing. Surely this can't be too difficult for the author to implement (he says, knowing hardly anything about JQuery)?

**Comment by chipgrafx** [comment]
kevsurf2003, I was not able to achieve this. We had to move forward with the project so clicking a Problem on the homepage simply takes you to the Solutions page but not to the specific Solution tab. Still waiting for the plugin author to chime in.

**Comment by digiguru** [comment]
I'm not the author, but we've been making some modifications. See #16 it's a way of "clicking links". An example is as follows:

``` javascript
$('[role="tab"]').has("a[href='#reviews']").first().trigger("click")
```

This says basically "Get all tabs" `[role="tab"]` that have a link called reviews `a[href='#reviews']`.

This will select 2 nodes, the accordion header and the list header. Next we select just the list: `.first()` and then trigger a `click`

Here is a helper function that would allow you to select any of the tabs by name.

``` javascript
function selectTab(tabname) {
    $('[role="tab"]').has("a[href='#" + tabname + "']").first().trigger("click");
}
```
