### ISSUE TITLE
Automatic change of the tabs

### ISSUE THREAD

**Issue by scarletish** [samsono/Easy-Responsive-Tabs-to-Accordion#6]
Hi, 

Thanks for releasing the tabs for free. 
I wanted to ask you, if there's a way to make the tabs change automatically (rotate). 

Thanks very much:)

**Comment by steveoliver** [comment]
@scarletish I think you should be able to achieve what you're after with regular jQuery -- programmatically triggering the click of each tab.

**Comment by samsono** [comment]
Agreed with scarletish.
