### ISSUE TITLE
Compatibility in internet explorer 9

### ISSUE THREAD

**Issue by mikezclements** [samsono/Easy-Responsive-Tabs-to-Accordion#60]
I tried this on IE9 but it seems that hash not working like #abouttab2 when navigating to through different tabs. Can you recommend me what to do?

**Comment by samsono** [comment]
It should work.

**Comment by mikezclements** [comment]
try to visit http://webthemez.com/demo/easy-responsive-tabs/Index.html in ie8 and ie9 and you will noticed hash not changing when navigating in different tabs.
